export const countryCodes = [
  { countryCode: "in", phoneCode: "91", countryName: "India" },
  { countryCode: "us", phoneCode: "1", countryName: "United States" },
  { countryCode: "ca", phoneCode: "1", countryName: "Canada" },
  { countryCode: "ru", phoneCode: "7", countryName: "Russia" },
  { countryCode: "kz", phoneCode: "7", countryName: "Kazakhstan" },
  { countryCode: "eg", phoneCode: "20", countryName: "Egypt" },
  { countryCode: "za", phoneCode: "27", countryName: "South Africa" },
  { countryCode: "gr", phoneCode: "30", countryName: "Greece" },
  { countryCode: "nl", phoneCode: "31", countryName: "Netherlands" },
  { countryCode: "be", phoneCode: "32", countryName: "Belgium" },
  { countryCode: "fr", phoneCode: "33", countryName: "France" },
  { countryCode: "es", phoneCode: "34", countryName: "Spain" },
  { countryCode: "hu", phoneCode: "36", countryName: "Hungary" },
  { countryCode: "it", phoneCode: "39", countryName: "Italy" },
  { countryCode: "ro", phoneCode: "40", countryName: "Romania" },
  { countryCode: "ch", phoneCode: "41", countryName: "Switzerland" },
  { countryCode: "at", phoneCode: "43", countryName: "Austria" },
  { countryCode: "gb", phoneCode: "44", countryName: "United Kingdom" },
  { countryCode: "dk", phoneCode: "45", countryName: "Denmark" },
  { countryCode: "se", phoneCode: "46", countryName: "Sweden" },
  { countryCode: "no", phoneCode: "47", countryName: "Norway" },
  { countryCode: "pl", phoneCode: "48", countryName: "Poland" },
  { countryCode: "de", phoneCode: "49", countryName: "Germany" },
  { countryCode: "pe", phoneCode: "51", countryName: "Peru" },
  { countryCode: "mx", phoneCode: "52", countryName: "Mexico" },
  { countryCode: "cu", phoneCode: "53", countryName: "Cuba" },
  { countryCode: "ar", phoneCode: "54", countryName: "Argentina" },
  { countryCode: "br", phoneCode: "55", countryName: "Brazil" },
  { countryCode: "cl", phoneCode: "56", countryName: "Chile" },
  { countryCode: "co", phoneCode: "57", countryName: "Colombia" },
  { countryCode: "ve", phoneCode: "58", countryName: "Venezuela" },
  { countryCode: "my", phoneCode: "60", countryName: "Malaysia" },
  { countryCode: "au", phoneCode: "61", countryName: "Australia" },
  { countryCode: "id", phoneCode: "62", countryName: "Indonesia" },
  { countryCode: "ph", phoneCode: "63", countryName: "Philippines" },
  { countryCode: "nz", phoneCode: "64", countryName: "New Zealand" },
  { countryCode: "sg", phoneCode: "65", countryName: "Singapore" },
  { countryCode: "th", phoneCode: "66", countryName: "Thailand" },
  { countryCode: "jp", phoneCode: "81", countryName: "Japan" },
  { countryCode: "kr", phoneCode: "82", countryName: "South Korea" },
  { countryCode: "vn", phoneCode: "84", countryName: "Vietnam" },
  { countryCode: "cn", phoneCode: "86", countryName: "China" },
  { countryCode: "tr", phoneCode: "90", countryName: "Turkey" },
  { countryCode: "pk", phoneCode: "92", countryName: "Pakistan" },
  { countryCode: "af", phoneCode: "93", countryName: "Afghanistan" },
  { countryCode: "lk", phoneCode: "94", countryName: "Sri Lanka" },
  { countryCode: "mm", phoneCode: "95", countryName: "Myanmar" },
  { countryCode: "ir", phoneCode: "98", countryName: "Iran" },
  { countryCode: "ma", phoneCode: "212", countryName: "Morocco" },
  { countryCode: "dz", phoneCode: "213", countryName: "Algeria" },
  { countryCode: "tn", phoneCode: "216", countryName: "Tunisia" },
  { countryCode: "ly", phoneCode: "218", countryName: "Libya" },
  { countryCode: "gm", phoneCode: "220", countryName: "Gambia" },
  { countryCode: "sn", phoneCode: "221", countryName: "Senegal" },
  { countryCode: "mr", phoneCode: "222", countryName: "Mauritania" },
  { countryCode: "ml", phoneCode: "223", countryName: "Mali" },
  { countryCode: "gn", phoneCode: "224", countryName: "Guinea" },
  { countryCode: "ci", phoneCode: "225", countryName: "Ivory Coast" },
  { countryCode: "bf", phoneCode: "226", countryName: "Burkina Faso" },
  { countryCode: "ne", phoneCode: "227", countryName: "Niger" },
  { countryCode: "tg", phoneCode: "228", countryName: "Togo" },
  { countryCode: "bj", phoneCode: "229", countryName: "Benin" },
  { countryCode: "mu", phoneCode: "230", countryName: "Mauritius" },
  { countryCode: "lr", phoneCode: "231", countryName: "Liberia" },
  { countryCode: "sl", phoneCode: "232", countryName: "Sierra Leone" },
  { countryCode: "gh", phoneCode: "233", countryName: "Ghana" },
  { countryCode: "ng", phoneCode: "234", countryName: "Nigeria" },
  { countryCode: "td", phoneCode: "235", countryName: "Chad" },
  {
    countryCode: "cf",
    phoneCode: "236",
    countryName: "Central African Republic",
  },
  { countryCode: "cm", phoneCode: "237", countryName: "Cameroon" },
  { countryCode: "cv", phoneCode: "238", countryName: "Cape Verde" },
  { countryCode: "st", phoneCode: "239", countryName: "Sao Tome and Principe" },
  { countryCode: "gq", phoneCode: "240", countryName: "Equatorial Guinea" },
  { countryCode: "ga", phoneCode: "241", countryName: "Gabon" },
  { countryCode: "cg", phoneCode: "242", countryName: "Republic of the Congo" },
  { countryCode: "cd", phoneCode: "243", countryName: "DR Congo" },
  { countryCode: "ao", phoneCode: "244", countryName: "Angola" },
  { countryCode: "gw", phoneCode: "245", countryName: "Guinea-Bissau" },
  {
    countryCode: "io",
    phoneCode: "246",
    countryName: "British Indian Ocean Territory",
  },
  { countryCode: "sc", phoneCode: "248", countryName: "Seychelles" },
  { countryCode: "sd", phoneCode: "249", countryName: "Sudan" },
  { countryCode: "rw", phoneCode: "250", countryName: "Rwanda" },
  { countryCode: "et", phoneCode: "251", countryName: "Ethiopia" },
  { countryCode: "so", phoneCode: "252", countryName: "Somalia" },
  { countryCode: "dj", phoneCode: "253", countryName: "Djibouti" },
  { countryCode: "ke", phoneCode: "254", countryName: "Kenya" },
  { countryCode: "tz", phoneCode: "255", countryName: "Tanzania" },
  { countryCode: "ug", phoneCode: "256", countryName: "Uganda" },
  { countryCode: "bi", phoneCode: "257", countryName: "Burundi" },
  { countryCode: "mz", phoneCode: "258", countryName: "Mozambique" },
  { countryCode: "zm", phoneCode: "260", countryName: "Zambia" },
  { countryCode: "mg", phoneCode: "261", countryName: "Madagascar" },
  { countryCode: "re", phoneCode: "262", countryName: "Réunion" },
  { countryCode: "zw", phoneCode: "263", countryName: "Zimbabwe" },
  { countryCode: "na", phoneCode: "264", countryName: "Namibia" },
  { countryCode: "mw", phoneCode: "265", countryName: "Malawi" },
  { countryCode: "ls", phoneCode: "266", countryName: "Lesotho" },
  { countryCode: "bw", phoneCode: "267", countryName: "Botswana" },
  { countryCode: "sz", phoneCode: "268", countryName: "Eswatini" },
  { countryCode: "km", phoneCode: "269", countryName: "Comoros" },
  { countryCode: "sh", phoneCode: "290", countryName: "Saint Helena" },
  { countryCode: "er", phoneCode: "291", countryName: "Eritrea" },
  { countryCode: "aw", phoneCode: "297", countryName: "Aruba" },
  { countryCode: "fo", phoneCode: "298", countryName: "Faroe Islands" },
  { countryCode: "gl", phoneCode: "299", countryName: "Greenland" },
  { countryCode: "gi", phoneCode: "350", countryName: "Gibraltar" },
  { countryCode: "pt", phoneCode: "351", countryName: "Portugal" },
  { countryCode: "lu", phoneCode: "352", countryName: "Luxembourg" },
  { countryCode: "ie", phoneCode: "353", countryName: "Ireland" },
  { countryCode: "is", phoneCode: "354", countryName: "Iceland" },
  { countryCode: "al", phoneCode: "355", countryName: "Albania" },
  { countryCode: "mt", phoneCode: "356", countryName: "Malta" },
  { countryCode: "cy", phoneCode: "357", countryName: "Cyprus" },
  { countryCode: "fi", phoneCode: "358", countryName: "Finland" },
  { countryCode: "bg", phoneCode: "359", countryName: "Bulgaria" },
  { countryCode: "lt", phoneCode: "370", countryName: "Lithuania" },
  { countryCode: "lv", phoneCode: "371", countryName: "Latvia" },
  { countryCode: "ee", phoneCode: "372", countryName: "Estonia" },
  { countryCode: "md", phoneCode: "373", countryName: "Moldova" },
  { countryCode: "am", phoneCode: "374", countryName: "Armenia" },
  { countryCode: "by", phoneCode: "375", countryName: "Belarus" },
  { countryCode: "ad", phoneCode: "376", countryName: "Andorra" },
  { countryCode: "mc", phoneCode: "377", countryName: "Monaco" },
  { countryCode: "sm", phoneCode: "378", countryName: "San Marino" },
  { countryCode: "va", phoneCode: "379", countryName: "Vatican City" },
  { countryCode: "ua", phoneCode: "380", countryName: "Ukraine" },
  { countryCode: "rs", phoneCode: "381", countryName: "Serbia" },
  { countryCode: "me", phoneCode: "382", countryName: "Montenegro" },
  { countryCode: "hr", phoneCode: "385", countryName: "Croatia" },
  { countryCode: "si", phoneCode: "386", countryName: "Slovenia" },
  {
    countryCode: "ba",
    phoneCode: "387",
    countryName: "Bosnia and Herzegovina",
  },
  { countryCode: "mk", phoneCode: "389", countryName: "North Macedonia" },
  { countryCode: "cz", phoneCode: "420", countryName: "Czech Republic" },
  { countryCode: "sk", phoneCode: "421", countryName: "Slovakia" },
  { countryCode: "li", phoneCode: "423", countryName: "Liechtenstein" },
  { countryCode: "fk", phoneCode: "500", countryName: "Falkland Islands" },
  { countryCode: "bz", phoneCode: "501", countryName: "Belize" },
  { countryCode: "gt", phoneCode: "502", countryName: "Guatemala" },
  { countryCode: "sv", phoneCode: "503", countryName: "El Salvador" },
  { countryCode: "hn", phoneCode: "504", countryName: "Honduras" },
  { countryCode: "ni", phoneCode: "505", countryName: "Nicaragua" },
  { countryCode: "cr", phoneCode: "506", countryName: "Costa Rica" },
  { countryCode: "pa", phoneCode: "507", countryName: "Panama" },
  {
    countryCode: "pm",
    phoneCode: "508",
    countryName: "Saint Pierre and Miquelon",
  },
  { countryCode: "ht", phoneCode: "509", countryName: "Haiti" },
  { countryCode: "gp", phoneCode: "590", countryName: "Guadeloupe" },
  { countryCode: "bo", phoneCode: "591", countryName: "Bolivia" },
  { countryCode: "gy", phoneCode: "592", countryName: "Guyana" },
  { countryCode: "ec", phoneCode: "593", countryName: "Ecuador" },
  { countryCode: "gf", phoneCode: "594", countryName: "French Guiana" },
  { countryCode: "py", phoneCode: "595", countryName: "Paraguay" },
  { countryCode: "mq", phoneCode: "596", countryName: "Martinique" },
  { countryCode: "sr", phoneCode: "597", countryName: "Suriname" },
  { countryCode: "uy", phoneCode: "598", countryName: "Uruguay" },
  { countryCode: "cw", phoneCode: "599", countryName: "Curaçao" },
  { countryCode: "tl", phoneCode: "670", countryName: "Timor-Leste" },
  { countryCode: "nf", phoneCode: "672", countryName: "Norfolk Island" },
  { countryCode: "bn", phoneCode: "673", countryName: "Brunei" },
  { countryCode: "nr", phoneCode: "674", countryName: "Nauru" },
  { countryCode: "pg", phoneCode: "675", countryName: "Papua New Guinea" },
  { countryCode: "to", phoneCode: "676", countryName: "Tonga" },
  { countryCode: "sb", phoneCode: "677", countryName: "Solomon Islands" },
  { countryCode: "vu", phoneCode: "678", countryName: "Vanuatu" },
  { countryCode: "fj", phoneCode: "679", countryName: "Fiji" },
  { countryCode: "pw", phoneCode: "680", countryName: "Palau" },
  { countryCode: "wf", phoneCode: "681", countryName: "Wallis and Futuna" },
  { countryCode: "ck", phoneCode: "682", countryName: "Cook Islands" },
  { countryCode: "nu", phoneCode: "683", countryName: "Niue" },
  { countryCode: "ws", phoneCode: "685", countryName: "Samoa" },
  { countryCode: "ki", phoneCode: "686", countryName: "Kiribati" },
  { countryCode: "nc", phoneCode: "687", countryName: "New Caledonia" },
  { countryCode: "tv", phoneCode: "688", countryName: "Tuvalu" },
  { countryCode: "pf", phoneCode: "689", countryName: "French Polynesia" },
  { countryCode: "tk", phoneCode: "690", countryName: "Tokelau" },
  { countryCode: "fm", phoneCode: "691", countryName: "Micronesia" },
  { countryCode: "mh", phoneCode: "692", countryName: "Marshall Islands" },
  { countryCode: "kp", phoneCode: "850", countryName: "North Korea" },
  { countryCode: "hk", phoneCode: "852", countryName: "Hong Kong" },
  { countryCode: "mo", phoneCode: "853", countryName: "Macau" },
  { countryCode: "kh", phoneCode: "855", countryName: "Cambodia" },
  { countryCode: "la", phoneCode: "856", countryName: "Laos" },
  { countryCode: "bd", phoneCode: "880", countryName: "Bangladesh" },
  { countryCode: "tw", phoneCode: "886", countryName: "Taiwan" },
  { countryCode: "mv", phoneCode: "960", countryName: "Maldives" },
  { countryCode: "lb", phoneCode: "961", countryName: "Lebanon" },
  { countryCode: "jo", phoneCode: "962", countryName: "Jordan" },
  { countryCode: "sy", phoneCode: "963", countryName: "Syria" },
  { countryCode: "iq", phoneCode: "964", countryName: "Iraq" },
  { countryCode: "kw", phoneCode: "965", countryName: "Kuwait" },
  { countryCode: "sa", phoneCode: "966", countryName: "Saudi Arabia" },
  { countryCode: "ye", phoneCode: "967", countryName: "Yemen" },
  { countryCode: "om", phoneCode: "968", countryName: "Oman" },
  { countryCode: "ps", phoneCode: "970", countryName: "Palestine" },
  { countryCode: "ae", phoneCode: "971", countryName: "United Arab Emirates" },
  { countryCode: "il", phoneCode: "972", countryName: "Israel" },
  { countryCode: "bh", phoneCode: "973", countryName: "Bahrain" },
  { countryCode: "qa", phoneCode: "974", countryName: "Qatar" },
  { countryCode: "bt", phoneCode: "975", countryName: "Bhutan" },
  { countryCode: "mn", phoneCode: "976", countryName: "Mongolia" },
  { countryCode: "np", phoneCode: "977", countryName: "Nepal" },
  { countryCode: "tj", phoneCode: "992", countryName: "Tajikistan" },
  { countryCode: "tm", phoneCode: "993", countryName: "Turkmenistan" },
  { countryCode: "az", phoneCode: "994", countryName: "Azerbaijan" },
  { countryCode: "ge", phoneCode: "995", countryName: "Georgia" },
  { countryCode: "kg", phoneCode: "996", countryName: "Kyrgyzstan" },
  { countryCode: "uz", phoneCode: "998", countryName: "Uzbekistan" },
];
